services:
  client:
    build:
      context: .
      dockerfile: Dockerfile-Client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - dev_net
    depends_on:
      - server
    environment:
      - NODE_ENV=development
      - VITE_SERVER_URL=http://localhost:5005

  server:
    build:
      context: .
      dockerfile: Dockerfile-Server
    ports:
      - "5005:5005"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - dev_net
    environment:
      - NODE_ENV=development

networks:
  dev_net:
    driver: bridge