FROM node:20

WORKDIR /app

# Copy package.json and package-lock.json files
COPY ./client/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client application
COPY ./client ./

# Expose the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]